---
name: DNSControl Action
description: Deploy your DNS configuration to multiple providers using GitHub Actions. Easily automate DNS updates across providers.
author: Amaan Ul Haq Siddiqui <amaanulhaq.s@outlook.com>
branding:
  icon: cloud
  color: orange
inputs:
  args:
    description: DNSControl command
    required: true
  config_file:
    description: Path to DNSControl configuration file.
    required: false
    default: 'dnsconfig.js'
  creds_file:
    description: Path to DNSControl credentials file.
    required: false
    default: 'creds.json'
outputs:
  output:
    description: The output of the dnscontrol command that was executed.
runs:
  using: docker
  image: 'Dockerfile'
