---
name: deploy

on:
  push:
    branches:
      - main

jobs:
  dnscontrol:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: DNSControl push
        uses: amaan-igs/dnscontrol-action@v1
        env:
          CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
        with:
          args: push
