---
name: Test

on: pull_request

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run ESLint
        uses: koenrh/actions/eslint@master
        with:
          args: dnsconfig.js

  dnscontrol:
    name: DNSControl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Preview
        uses: amaan-igs/dnscontrol-action@v1
        env:
          CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
        with:
          args: preview
